// Live job-board fetch. OWNER: backend.
//
// Greenhouse and Lever both expose PUBLIC, UNAUTHENTICATED job board APIs.
// Verified live 2026-08-08:
//   boards-api.greenhouse.io/v1/boards/newrelic/jobs  -> 200, 8 Portland roles
//   api.lever.co/v0/postings/smarsh?mode=json         -> 200, 3 Portland roles
//
// This is why the job list is a real feed and not a hand-typed file. The PRD
// cut "live scraping" to avoid scraping infra — there is none here, these are
// documented JSON endpoints. We still commit a snapshot (data/portland-jobs.json,
// regenerated by scripts/snapshot-jobs.mjs) as the demo fallback.

const TIMEOUT_MS = 6000;
const CACHE_MS = 10 * 60 * 1000;

// Add boards here. A token that 404s is skipped silently — no need to prune.
// Find a token: it's the slug in the company's public board URL.
export const SOURCES = [
  { type: 'greenhouse', token: 'newrelic', company: 'New Relic' },
  { type: 'greenhouse', token: 'vacasa', company: 'Vacasa' },
  { type: 'greenhouse', token: 'airship', company: 'Airship' },
  { type: 'greenhouse', token: 'jamasoftware', company: 'Jama Software' },
  { type: 'greenhouse', token: 'zoominfo', company: 'ZoomInfo' },
  { type: 'lever', token: 'smarsh', company: 'Smarsh' },
];

// Portland metro, plus the remote buckets a Portlander is actually eligible for.
const METRO = /portland|oregon|,\s*or\b|beaverton|hillsboro|gresham|tigard|lake oswego|vancouver,\s*wa/i;
const REMOTE_OK = /remote\s*[-–]\s*(us|united states|west coast|usa)/i;

function classify(location) {
  // Multi-city postings list every office semicolon-separated, so a Portland
  // role can render as "Bethesda, Maryland; ...". Surface the local one.
  const segments = String(location).split(';').map((s) => s.trim()).filter(Boolean);
  const local = segments.find((s) => METRO.test(s));

  if (local) {
    const others = segments.length - 1;
    return {
      keep: true,
      remote: false,
      display: others > 0 ? `${local} (+${others} other location${others > 1 ? 's' : ''})` : local,
    };
  }
  if (REMOTE_OK.test(location)) return { keep: true, remote: true, display: segments[0] || location };
  return { keep: false, remote: false, display: location };
}

async function getJson(url) {
  const res = await fetch(url, {
    headers: { Accept: 'application/json', 'User-Agent': 'skills-bridge-pdx/0.1 (hackathon)' },
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function fetchGreenhouse({ token, company }) {
  const data = await getJson(`https://boards-api.greenhouse.io/v1/boards/${token}/jobs`);
  return (data.jobs || []).map((job) => ({
    id: `gh-${token}-${job.id}`,
    title: (job.title || '').trim(),
    company: job.company_name || company,
    location: job.location?.name || '',
    url: job.absolute_url,
    postedAt: (job.first_published || job.updated_at || '').slice(0, 10),
    source: 'Greenhouse public job board API',
  }));
}

async function fetchLever({ token, company }) {
  const data = await getJson(`https://api.lever.co/v0/postings/${token}?mode=json`);
  return (data || []).map((job) => ({
    id: `lv-${token}-${job.id}`,
    title: (job.text || '').trim(),
    company,
    location: job.categories?.location || '',
    url: job.hostedUrl,
    postedAt: job.createdAt ? new Date(job.createdAt).toISOString().slice(0, 10) : '',
    source: 'Lever public postings API',
  }));
}

const FETCHERS = { greenhouse: fetchGreenhouse, lever: fetchLever };

let cache = { at: 0, jobs: null };

/**
 * Every currently-open Portland-metro role across all SOURCES.
 * allSettled, so one dead board can't take down the endpoint.
 * @returns {Promise<{jobs: object[], boardsOk: number, boardsTried: number}>}
 */
export async function fetchPortlandJobs({ force = false } = {}) {
  if (!force && cache.jobs && Date.now() - cache.at < CACHE_MS) {
    return { ...cache.jobs, cached: true };
  }

  const results = await Promise.allSettled(
    SOURCES.map((source) => FETCHERS[source.type](source))
  );

  const jobs = [];
  let boardsOk = 0;
  for (const [i, result] of results.entries()) {
    if (result.status !== 'fulfilled') {
      console.warn(`[boards] ${SOURCES[i].token} failed: ${result.reason?.message}`);
      continue;
    }
    boardsOk++;
    for (const job of result.value) {
      const { keep, remote, display } = classify(job.location);
      // `location` becomes the Portland-first display string; the raw board
      // value stays on `locationRaw` so nothing is quietly discarded.
      if (keep && job.title && job.url) {
        jobs.push({ ...job, location: display, locationRaw: job.location, remote });
      }
    }
  }

  // Metro roles ahead of remote ones — "open in Portland" should mean it.
  jobs.sort((a, b) => Number(a.remote) - Number(b.remote) || a.title.localeCompare(b.title));

  const payload = { jobs, boardsOk, boardsTried: SOURCES.length };
  cache = { at: Date.now(), jobs: payload };
  return { ...payload, cached: false };
}
