// Live job-board fetch. OWNER: backend.
//
// Greenhouse, Lever, SmartRecruiters and Ashby all expose PUBLIC,
// UNAUTHENTICATED job board APIs. Verified live 2026-08-08:
//   boards-api.greenhouse.io/v1/boards/newrelic/jobs           -> 200, 8 Portland roles
//   api.lever.co/v0/postings/smarsh?mode=json                  -> 200, 3 Portland roles
//   api.smartrecruiters.com/v1/companies/TenderlyHospice/...   -> 200, 2 Portland roles
//   api.ashbyhq.com/posting-api/job-board/omadaai              -> 200, 9 Portland roles
//
// This is why the job list is a real feed and not a hand-typed file. The PRD
// cut "live scraping" to avoid scraping infra — there is none here, these are
// documented JSON endpoints. We still commit a snapshot (data/portland-jobs.json,
// regenerated by scripts/snapshot-jobs.mjs) as the demo fallback.

const TIMEOUT_MS = 6000;
const CACHE_MS = 10 * 60 * 1000;

// Add boards here. A token that 404s is skipped silently — no need to prune.
// Find a token: it's the slug in the company's public board URL.
//
// Sector labels are deliberate. The first six boards were all software, which
// made the app useless for anyone whose ONET match isn't a tech occupation —
// "Registered Nurses" returned zero. Everything below was found by probing
// candidate tokens and kept only if it returned 200 with real Portland-metro
// postings; sector coverage was the tiebreak, not headcount.
export const SOURCES = [
  // Tech (original set)
  { type: 'greenhouse', token: 'newrelic', company: 'New Relic' },
  { type: 'greenhouse', token: 'vacasa', company: 'Vacasa' },
  { type: 'greenhouse', token: 'airship', company: 'Airship' },
  { type: 'greenhouse', token: 'jamasoftware', company: 'Jama Software' },
  { type: 'greenhouse', token: 'zoominfo', company: 'ZoomInfo' },
  { type: 'lever', token: 'smarsh', company: 'Smarsh' },
  { type: 'ashby', token: 'prophetic-technologies', company: 'Prophetic' },

  // Healthcare — the sector the demo most conspicuously lacked.
  { type: 'greenhouse', token: 'headlandsresearch', company: 'Headlands Research' },
  { type: 'greenhouse', token: 'townncountryvet', company: 'Town & Country Animal Hospital' },
  { type: 'greenhouse', token: 'heartflowinc', company: 'Heartflow' },
  { type: 'greenhouse', token: 'joinaffect', company: 'Affect' },
  { type: 'smartrecruiters', token: 'ConnectedHomeHealthHospice', company: 'Connected Home Health & Hospice' },
  { type: 'smartrecruiters', token: 'TenderlyHospice', company: 'Tenderly Hospice' },
  { type: 'smartrecruiters', token: 'trinitashcs', company: 'Trinitas Healthcare Staffing' },
  { type: 'smartrecruiters', token: 'KARecruitingInc', company: 'K.A. Recruiting' },
  { type: 'smartrecruiters', token: 'Dungarvin', company: 'Dungarvin' },

  // Trades, property and skilled maintenance
  { type: 'greenhouse', token: 'ambiententerprises', company: 'Ambient Enterprises (Johnson Barrow)' },
  { type: 'greenhouse', token: 'mgproperties', company: 'MG Properties' },
  { type: 'smartrecruiters', token: 'REXEL1', company: 'Rexel / Platt Electric' },

  // Engineering, manufacturing and apparel
  { type: 'greenhouse', token: 'terraphaseengineeringinc', company: 'Terraphase Engineering' },
  { type: 'greenhouse', token: 'perryellisinternational', company: 'Perry Ellis International' },
  { type: 'smartrecruiters', token: 'CoffmanEngineersInc', company: 'Coffman Engineers' },
  { type: 'smartrecruiters', token: 'FortuneBrands', company: 'Fortune Brands' },

  // Government / public service
  { type: 'smartrecruiters', token: 'PortlandOregon-NationalGuard', company: 'Oregon Army National Guard' },

  // Nonprofit and education
  { type: 'greenhouse', token: 'ohsufoundation', company: 'OHSU Foundation' },

  // Finance, accounting and professional services
  { type: 'lever', token: 'Aprio', company: 'Aprio' },
  { type: 'greenhouse', token: 'merceradvisors', company: 'Mercer Advisors' },

  // Retail, food and field sales — the closest analogues to an account-manager résumé.
  { type: 'lever', token: 'cscgeneration-2', company: 'Sur La Table (CSC Generation)' },
  { type: 'lever', token: 'beautybarrage', company: 'Beauty Barrage' },
  { type: 'ashby', token: 'omadaai', company: 'Omada' },
];

// Portland metro, plus the remote buckets a Portlander is actually eligible for.
const METRO = /portland|oregon|,\s*or\b|beaverton|hillsboro|gresham|tigard|lake oswego|vancouver,\s*wa/i;
// Portland, MAINE is a real hiring hub (and "South Portland, ME" is common).
// With only local tech boards this never came up; with national employers it
// silently injects fake "Portland" roles, so it has to be excluded by name.
const NOT_METRO = /maine|,\s*me\b/i;
const REMOTE_OK = /remote\s*[-–]\s*(us|united states|west coast|usa)/i;

function classify(location) {
  // Multi-city postings list every office semicolon-separated, so a Portland
  // role can render as "Bethesda, Maryland; ...". Surface the local one.
  const segments = String(location).split(';').map((s) => s.trim()).filter(Boolean);
  const local = segments.find((s) => METRO.test(s) && !NOT_METRO.test(s));

  if (local) {
    const others = segments.length - 1;
    return {
      keep: true,
      remote: false,
      display: others > 0 ? `${local} (+${others} other location${others > 1 ? 's' : ''})` : local,
    };
  }
  if (REMOTE_OK.test(location)) return { keep: true, remote: true, display: segments[0] || location };
  return { keep: false, remote: false, display: location };
}

async function getJson(url) {
  const res = await fetch(url, {
    headers: { Accept: 'application/json', 'User-Agent': 'skills-bridge-pdx/0.1 (hackathon)' },
    signal: AbortSignal.timeout(TIMEOUT_MS),
  });
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function fetchGreenhouse({ token, company }) {
  const data = await getJson(`https://boards-api.greenhouse.io/v1/boards/${token}/jobs`);
  return (data.jobs || []).map((job) => ({
    id: `gh-${token}-${job.id}`,
    title: (job.title || '').trim(),
    company: job.company_name || company,
    location: job.location?.name || '',
    url: job.absolute_url,
    postedAt: (job.first_published || job.updated_at || '').slice(0, 10),
    source: 'Greenhouse public job board API',
  }));
}

async function fetchLever({ token, company }) {
  const data = await getJson(`https://api.lever.co/v0/postings/${token}?mode=json`);
  return (data || []).map((job) => ({
    id: `lv-${token}-${job.id}`,
    title: (job.text || '').trim(),
    company,
    location: job.categories?.location || '',
    url: job.hostedUrl,
    postedAt: job.createdAt ? new Date(job.createdAt).toISOString().slice(0, 10) : '',
    source: 'Lever public postings API',
  }));
}

// SmartRecruiters is where the local healthcare, hospice and public-sector
// employers actually post — none of them are on Greenhouse or Lever.
//
// It's the only one of the four that pages: limit=100 is the API max, and
// national employers here run past it (Rexel 686, Dungarvin 303). Page 1 tells
// us totalFound, then the rest go out in parallel. Capped, because a board with
// thousands of franchise reqs isn't worth eight round-trips on a 6s budget.
const SR_PAGE = 100;
const SR_MAX_PAGES = 8;

async function fetchSmartRecruiters({ token, company }) {
  const url = (offset) =>
    `https://api.smartrecruiters.com/v1/companies/${token}/postings?limit=${SR_PAGE}&offset=${offset}`;

  const first = await getJson(url(0));
  const pages = Math.min(Math.ceil((first.totalFound || 0) / SR_PAGE), SR_MAX_PAGES);
  const rest = await Promise.all(
    Array.from({ length: Math.max(pages - 1, 0) }, (_, i) => getJson(url((i + 1) * SR_PAGE)))
  );

  const postings = [first, ...rest].flatMap((page) => page.content || []);
  return postings.map((job) => ({
    id: `sr-${token}-${job.id}`,
    // Prefer our display name: SmartRecruiters identifiers are often the
    // franchise/brand string ("Portland Oregon- National Guard"), not a name.
    company,
    title: (job.name || '').trim(),
    location: job.location?.fullLocation
      || [job.location?.city, job.location?.region].filter(Boolean).join(', '),
    url: `https://jobs.smartrecruiters.com/${job.company?.identifier || token}/${job.id}`,
    postedAt: (job.releasedDate || '').slice(0, 10),
    source: 'SmartRecruiters public postings API',
  }));
}

async function fetchAshby({ token, company }) {
  const data = await getJson(`https://api.ashbyhq.com/posting-api/job-board/${token}`);
  return (data.jobs || [])
    .filter((job) => job.isListed !== false)
    .map((job) => ({
      id: `ab-${token}-${job.id}`,
      title: (job.title || '').trim(),
      company,
      // Semicolon-join so classify()'s multi-city logic surfaces the local office.
      location: [job.location, ...(job.secondaryLocations || []).map((l) => l?.location || l)]
        .filter(Boolean)
        .join('; '),
      url: job.jobUrl || job.applyUrl,
      postedAt: (job.publishedAt || '').slice(0, 10),
      source: 'Ashby public job board API',
    }));
}

const FETCHERS = {
  greenhouse: fetchGreenhouse,
  lever: fetchLever,
  smartrecruiters: fetchSmartRecruiters,
  ashby: fetchAshby,
};

let cache = { at: 0, jobs: null };

/**
 * Every currently-open Portland-metro role across all SOURCES.
 * allSettled, so one dead board can't take down the endpoint.
 * @returns {Promise<{jobs: object[], boardsOk: number, boardsTried: number}>}
 */
export async function fetchPortlandJobs({ force = false } = {}) {
  if (!force && cache.jobs && Date.now() - cache.at < CACHE_MS) {
    return { ...cache.jobs, cached: true };
  }

  const results = await Promise.allSettled(
    SOURCES.map((source) => FETCHERS[source.type](source))
  );

  const jobs = [];
  let boardsOk = 0;
  for (const [i, result] of results.entries()) {
    if (result.status !== 'fulfilled') {
      console.warn(`[boards] ${SOURCES[i].token} failed: ${result.reason?.message}`);
      continue;
    }
    boardsOk++;
    for (const job of result.value) {
      const { keep, remote, display } = classify(job.location);
      // `location` becomes the Portland-first display string; the raw board
      // value stays on `locationRaw` so nothing is quietly discarded.
      if (keep && job.title && job.url) {
        jobs.push({ ...job, location: display, locationRaw: job.location, remote });
      }
    }
  }

  // Metro roles ahead of remote ones — "open in Portland" should mean it.
  jobs.sort((a, b) => Number(a.remote) - Number(b.remote) || a.title.localeCompare(b.title));

  const payload = { jobs, boardsOk, boardsTried: SOURCES.length };
  cache = { at: Date.now(), jobs: payload };
  return { ...payload, cached: false };
}
